resolver: lts-18.23
packages:
- example-client
- hackage-repo-tool
- hackage-root-tool
- hackage-security
- hackage-security-HTTP
- hackage-security-curl
- hackage-security-http-client
- precompute-fileinfo

flags:
  hackage-repo-tool:
    use-old-time: false

extra-deps:
- optparse-applicative-0.15.1.0@sha256:29ff6146aabf54d46c4c8788e8d1eadaea27c94f6d360c690c5f6c93dac4b07e,4810

