resolver: lts-7.14
packages:
- example-client
- hackage-repo-tool
- hackage-root-tool
- hackage-security
- hackage-security-HTTP
- hackage-security-curl
- hackage-security-http-client
- precompute-fileinfo
extra-deps:
- http-client-0.5.5
